### ISSUE TITLE
Should Divider use minHeight instead of Height?

### ISSUE THREAD

**Issue by StephenHaney** [modulz/radix#105]
Here's a Divider with `min-height: 1px;` in a parent with a `max-height`... looks great:
![image](https://user-images.githubusercontent.com/4045376/52380386-64359a80-2a22-11e9-9247-065e06174bc6.png)

Divider with `height: 1px` (and parent with a `max-height` set)... it disappears as it has no content:
![image](https://user-images.githubusercontent.com/4045376/52380397-6ac41200-2a22-11e9-8523-f7f69ba54a0f.png)

It's currently set to use height and so it disappears in max-height parents.

**Comment by peduarte** [comment]
@StephenHaney Hey 👋 

I'm not sure I understand this issue. I tried to [replicate it](https://jsbin.com/fiwiwegape/edit?html,css,output) but couldn't. Can you provide an example?

The only thing I could thing of is if this was inside a Flex Container and therefore needed `flex-shrink: 0` so it doens't shrink?

**Comment by colmtuite** [comment]
Yeah this is to do with structure. It sounds like it's inside a flex container, which shouldn't be the case, based on the picture.

If it must be inside a flex container (not the case), then it should go inside a `Box`, to prevent it from collapsing.

**Comment by peduarte** [comment]
Ok, that's what I thought.
