### ISSUE TITLE
Visual tweakz

### ISSUE THREAD

**Issue by colmtuite** [modulz/radix#132]
Making the styleguide pagez pop

- Make the sidebar `250px` width
- Put main content inside a `<Container size="2">` so it's centered in the remaining space (minus the sidebar)
- Make menu items `35px` tall (I had the 31px exclusively for the layer tree. I thought all other menu items would be `25px` or `35px`).
- Give menu items `25px` left and right padding
- Make sidebar headings `gray600`...I think that's `5` in your fancy new scale? They could either be dark and bold if you prefer. But they can't stay as they are.
- The main text in tables should be one notch smaller
- Can we add our custom scrollbar to the sidebar? The same one we're using throughout the core product

e voila!

<img width="2048" alt="Screenshot 2019-06-24 at 22 36 01" src="https://user-images.githubusercontent.com/805073/60055930-25edfe80-96d7-11e9-963f-6b220a0f034c.png">

**Comment by peduarte** [comment]
Much better ✨ 

I'll address the following in different PRs:
- Custom Scrollbar
- `MenuItem` updates
