### ISSUE TITLE
Update `MenuItem` Component

### ISSUE THREAD

**Issue by peduarte** [modulz/radix#136]
From @colmtuite  on #132 
> Make menu items 35px tall (I had the 31px exclusively for the layer tree. I thought all other menu items would be 25px or 35px).
> Give menu items 25px left and right padding
> Should be either `25px` or `35px` height

@colmtuite what other requirements? Is the padding related to the height?

**Comment by colmtuite** [comment]
My head is not clear enough right now to be making decisions about the MenuItem API, but off the top of my head, I think the padding should be set with utility props. I've seen all sorts of padding values for various MenuItem content layouts.

**Comment by peduarte** [comment]
@colmtuite we'll go with that approach for now then 👍
