### ISSUE TITLE
Move Icon related packages out

### ISSUE THREAD

**Issue by peduarte** [modulz/radix#159]
Hey @loklaan ,

I think we should move the Icon related packages back to its own repo. Sorry about this, I know I asked to put them in here initially 🤦‍♂ 

But now since things are changing a lot in Radix I think it will make more sense this way.

Would you mind tackling that when you get a chance, please? I think you'll be much more efficient at doing this than me.

Thanks a lot!

**Comment by loklaan** [comment]
@peduarte No worries.

Could you elaborate on the reasons, for posterity's sake?

**Comment by peduarte** [comment]
Absolutely. 

Iteration 
Quite often I’m iterating with how Radix and website are built and work together. Next I wanna try a gatsby theme. Having icon packages in there means I need to also consider side effects and ensuring nothing I do impacts that 

Modulz output
I’d like this repo to try and resemble what the Modulz output would be like. Which is a design system and docs. 

Productivity
The icon library is pretty stable and as a result not much work is done on there. 
Radix, website and Radix System on the other hand are heavily WIP. Multiple commits a day and releases a week. As well as many Netlify builds per week. 
Having them all as a monorepo requires pre-building them all and as a result everything takes much longer. 

Extras
- I also want to remove commilint, this library still in alpha and it’s slowing me down. Once things are more stable I’ll add back in as well as automated change log 
- And finally, for simplicity sake. As the team grows I’d like the component team to just focus on components. By removing icon related stuff it’ll simplify onboarding

**Comment by peduarte** [comment]
@benoitgrelard Hey do you think you could take this one? It needs to be moved to this repo: https://github.com/modulz/radix-icons
