### ISSUE TITLE
Full accessibility overhaul

### ISSUE THREAD

**Issue by colmtuite** [modulz/radix#16]
Loop back through all the components and make sure to add and scrutinise:

- Markup structure
- Aria roles
- Apt use of VisuallyHidden wrapper components
- Other screenreader attributes
- Keyboard shortcuts
- Focus states
- Cross browser/platform/device

**Comment by peduarte** [comment]
👍 

Which conformance level are we targeting? (A, AA or AAA)

**Comment by colmtuite** [comment]
I think it depends on the component. We can close this now and do this incrementally over time
