### ISSUE TITLE
Weird Tooltip hover in Safari and Firefox

### ISSUE THREAD

**Issue by vladmoroz** [modulz/radix#167]
When hovering or focusing a tooltip without animations, it jumps from elsewhere for a frame or two before it's positioned correctly. This is reproduced on macOS Safari and Firefox.

Here's a [video](https://upload.vladmoroz.com/safari-tooltip-bug.mov)

**Comment by vladmoroz** [comment]
Just noticed this happens with the Popover as well

**Comment by peduarte** [comment]
I think this is related to our low level placement logic. Will investigate.

**Comment by benoitgrelard** [comment]
This was closed via modulz/primitives#116 and new primitives being updated in radix.
