### ISSUE TITLE
The focus-lock's refToFocusOnClose prop will trigger native html focus events but not react focus events

### ISSUE THREAD

**Issue by hadihallak** [modulz/radix#169]
Just as the title says, when using the refToFocusOnClose prop in the popover the element will only trigger native focus events and not react ones

I've made a sandbox with details in here:
https://codesandbox.io/s/angry-thompson-zfkit

**Comment by peduarte** [comment]
Thanks Abdul, we’ll take a look at this. 

/cc @benoitgrelard

**Comment by benoitgrelard** [comment]
@hadihallak there's been a lot of changes on this front recently, would you be able to check if this is still an issue for you with the latest version of everything?

**Comment by benoitgrelard** [comment]
bump @hadihallak 🙂

**Comment by hadihallak** [comment]
@benoitgrelard Just tested it and it's working really well. Nicely done 💯 
Just one note, it seems like the refToFocusOnClose only works when pressing Esc? normal click outside behavior doesn't focus anything on close. Is this intentional?

Closing this issue as this has been fixed.

**Comment by benoitgrelard** [comment]
Hey @hadihallak yes this is intentional although it will actually depend on the value of `shouldBlockOutsideClick` prop too.

Basically if clicks aren't blocked we want to let people focus where they are trying to.
However, if clicks are blocked, then the focus would be returned normally.
