### ISSUE TITLE
Refactor LinkArrow from marketing into reusable Radix component

### ISSUE THREAD

**Issue by colmtuite** [modulz/radix#17]

**Comment by colmtuite** [comment]
Add a second size?

**Comment by benoitgrelard** [comment]
@colmtuite @peduarte is this still valid or can we close it?

**Comment by peduarte** [comment]
Not sure, we're currently working on new marketing stuff and will most likely have to go back to Radix, so Im happy to close this as it's an old issue and might not be relevant anymore.

Will wait for @colmtuite to validate

**Comment by benoitgrelard** [comment]
Yeah it's a really old issues so thought I'd ask.

**Comment by colmtuite** [comment]
I guess we'll need to either drop this, or do it in the marketing repo, because it won't be possible in Modulz.

So yeah I guess we can close this.
