### ISSUE TITLE
Popover collisions aren't always prevented

### ISSUE THREAD

**Issue by vladmoroz** [modulz/radix#170]
The popover tends to act stubbornly for the first time it’s supposed to reposition itself in order to prevent collision with viewport edges. In most cases, it doesn't reposition itself when you open it for the first time. Next time it’s opened, its position is just fine.

See the [screen recording](https://upload.vladmoroz.com/popover-collision.mov). To reproduce, try opening a popover near viewport edges.

**Comment by peduarte** [comment]
Hey @vladmoroz thanks for this. Can you raise this in the Primitives Repo please? 

We're not ready to discuss this with the entire world _just yet_ 😉
