### ISSUE TITLE
Textarea needs resize: vertical.

### ISSUE THREAD

**Issue by StephenHaney** [modulz/radix#189]
From Colm originally.

**Comment by benoitgrelard** [comment]
@colmtuite are you thinking that this is true of all textareas in modulz? If so then the change would be done in Radix, otherwise if we want to retain more flexibility (ie. sometimes still allow horizontal) we should do the change in Modulz instead.

**Comment by colmtuite** [comment]
I think it should be changed in the primitive actually. If we're setting `width: 100%`, it doesn't make sense to allow horizontal resizing.

**Comment by benoitgrelard** [comment]
@peduarte what do you think here?

**Comment by peduarte** [comment]
Not sure it belongs in Primitive, its way too low level. But happy to add it to Radix 👍

**Comment by benoitgrelard** [comment]
Doing some triaging, what's the decision on this? If it's done in Radix, it would have to be exposed in Modulz too long term.

**Comment by peduarte** [comment]
Adding this setting to Modulz is just odd. This is an element's attribute so maybe better to not do anything and leave it up to the consumer to decide what to do?

**Comment by benoitgrelard** [comment]
I would tend to agree. @colmtuite?

**Comment by vladmoroz** [comment]
If we don't expose it in Modulz, this means they would need to set the resize property _all_ the time.

Is it unreasonable to say that there's no practical use for horizontal resize on the textarea? I don't see a case for it to be fair and would vote to put it on Primitive as well.

**Comment by peduarte** [comment]
I supposed _we could_ put it on the Primitive as long as it can be overriden.

**Comment by benoitgrelard** [comment]
Makes sense, shall we go with that then? I think if it’s just a default Let’s do it.

**Comment by colmtuite** [comment]
> Is it unreasonable to say that there's no practical use for horizontal resize on the textarea?

Not unreasonable at all imo. We should bake it into the primitive, and not expose it in Modulz.

If users want to override it in their product, fine. But I don't think we need to worry about this. Textareas should always just resize vertically imo.

**Comment by benoitgrelard** [comment]
Cool, I'll add to the Primitive
