### ISSUE TITLE
ToggleButton: consider using box shadow for consistency

### ISSUE THREAD

**Issue by benoitgrelard** [modulz/radix#191]
This was migrated from a TODO:

> This isn't too straightforward though. We can’t reliably center elements inside `ToggleButton` — like same height icons — unless we remove the borders and use box-shadows instead, but also can’t remove the borders and use box-shadows, because we use negative margins to compensate for adjacent border.

**Comment by colmtuite** [comment]
I'm not sure what this is about? What issue are we trying to solve here?

**Comment by benoitgrelard** [comment]
I think we can close this now, as nobody's claimed work needed on this.
