### ISSUE TITLE
GhostButton needs a bigger size variant

### ISSUE THREAD

**Issue by peduarte** [modulz/radix#192]
We used to have a bigger size for GhostButton, but [was removed here](https://github.com/modulz/radix/pull/175/files#diff-1c398bdf10383c999cbf7c4351404205)

We need to add this back so we can render 25px Icons in them 👍

**Comment by vladmoroz** [comment]
Hey Pedro
Why do we need it?

**Comment by peduarte** [comment]
We need it so we can use GhostButtons in the Mini Nav, the icons there are 25px

**Comment by colmtuite** [comment]
Yeah I'm fine with adding that size back. Looks like we will need it (at least for a while) for the mininav.
