### ISSUE TITLE
Implement Primitives Table

### ISSUE THREAD

**Issue by peduarte** [modulz/radix#207]
Let's talk design @vladmoroz @colmtuite 🌈

**Comment by colmtuite** [comment]
What do we discuss here?

**Comment by peduarte** [comment]
We need a Radix Table component. Will be used on the Docs as well as the App. 

Currently we have one being used on the Docs, so that would be our starting point 😃

**Comment by colmtuite** [comment]
Oh I see. Yeah that's fine to use, there should be no need to discuss the design of it afaik? Unless I'm overlooking something important, can we just whack in any reasonable design for now?

**Comment by peduarte** [comment]
The Radix Table on the Docs is different than the Tables on the App, ideally they should be the same, or use a variant.  

So, I think there’s some need to agree on what the Radix Table will look like so that it can be used consistently across the Docs and App?

Unless you’re ok with the current design of the table and with the App not using it?

**Comment by colmtuite** [comment]
They should be the same imo.

You can just choose one or the other, then make them all look like that. Choose whichever you think looks nicer, and tweak it a little if you like.

Then we can loop back around later and polish it up.

**Comment by peduarte** [comment]
Sounds good 🙂
