### ISSUE TITLE
Menu component showing blank area when the properties change dynamically

### ISSUE THREAD

**Issue by paulocfjunior** [modulz/radix#218]
Hello, I noticed that when the properties change dynamically inside of the Menu component, its size is not automatically adjusted and it shows a blank area below.

I got this behavior originally when I tried to use the Menu component to show autocomplete suggestions, but I could reproduce directly on the Radix docs, using the [live documentation](https://radix.modulz.app/docs/menu/), with this very simple code snippet:

```jsx
() => {
  const targetRef = React.useRef();
  const [options, setOptions] = React.useState(['Option 1', 'Option 2', 'Option 3'])

  setTimeout(() => {
    setOptions(['Option 1'])
  }, 1000)

  return (
    <Box height="93px">
      <div ref={targetRef} />
      <Menu isOpen buttonRef={targetRef} unstable__disableLock>
        {options.map(o => <MenuItem label={o} />)}
      </Menu>
    </Box>
  );
};
```

Here's a GIF to demonstrate the result of this code:

![MenuRadix](https://user-images.githubusercontent.com/38889364/75810193-e3ea8180-5d68-11ea-8550-88c2e8b2e4e9.gif)

When I debugged the component, I noticed that it receives a fixed height, then I tried to remove it on the inspector and the menu started behaving as I expected.

I'd like to know if it's a bug, or if I'm not using it correctly.

**Comment by benoitgrelard** [comment]
Hey @paulocfjunior thanks for the report, this is most likely a bug in our lower-level primitives layer.
I will log it there.

**Comment by benoitgrelard** [comment]
I'll update this issue once it's resolved and a new version of radix is released.
Please also bear in mind that radix is still in early beta for now.

**Comment by paulocfjunior** [comment]
Sure, no problem, thank you!

**Comment by benoitgrelard** [comment]
Hi @paulocfjunior this has now been fixed as part of the latest release `@modulz/radix@0.0.1-beta.31`.
