### ISSUE TITLE
Table headers misaligned in Safari

### ISSUE THREAD

**Issue by raunofreiberg** [modulz/radix#239]
I noticed that `text-align: unset` does not work as intended on tables in Safari (headers are aligned to center, whereas on Chrome they are on the left):

![image](https://user-images.githubusercontent.com/23662329/77761691-17a38900-7041-11ea-9c21-da9c08bdab12.png)

The solution would be to set `text-align: left` explicitly.

I did not find this property in the [Table component in this repo](https://github.com/modulz/radix/blob/master/packages/radix/src/components/Table.tsx), so I the assume the fix has to be done in `@modulz/primitives` which I don't have access to. This way any Tables built on top of `@modulz/primitives` would be consistent.

**Comment by peduarte** [comment]
Hm, interesting. Thanks for that!

**Comment by benoitgrelard** [comment]
Sure I'll take it! Thanks for reporting @raunofreiberg

**Comment by peduarte** [comment]
This shoud've been fixed now! :)
