### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by codejamninja** [modulz/radix#242]
Are there plans for react native support? If the primitives are built in react native, will everything else work?

**Comment by peduarte** [comment]
Hey @codejamninja 👋 

We do have plans to support React Native, but this is rather a long term one. 

At the moment we're not sure how it'll impact the current version of primitives. It may be a whole new package. It's too early to know. 

In any case, this effort will take place once we've gotten things right for the web first. 

Thanks!

**Comment by rafarc21** [comment]
Hi, 

Has this support been reached?

**Comment by colmtuite** [comment]
Nope. We have no plans to support RN.
