### ISSUE TITLE
Modulz Primatives

### ISSUE THREAD

**Issue by codejamninja** [modulz/radix#243]
What is the license for the following project?

https://www.npmjs.com/package/@modulz/primitives

Is there any way it can be shared with the community?

**Comment by peduarte** [comment]
@codejamninja Hey 👋 

We're still figuring out which license it will be.  Primitives is currently a private repo and it's not open sourced. 

It's heavily WIP and there are breaking changes on a daily basis 😄 

The main purpose of Primitives right now is to serve the need of Modulz, and to be exclusively used by Modulz. 

Once the product is more mature, and we have a clearer idea on whether it'll be open source, we'll announce it to everyone.

Thanks so much!

**Comment by adenta** [comment]
Whats the status on this? Radix looks cool, but I don't want to have to style _everything_ myself. Will this repo let me build on top of radix without having to have an opinion on every component?

**Comment by benoitgrelard** [comment]
> Whats the status on this? Radix looks cool, but I don't want to have to style _everything_ myself. Will this repo let me build on top of radix without having to have an opinion on every component?

We have been talking about potentially building a new layer on top primitives, separate from the design system, exactly for your use-case @adenta. Basically something pre-styled which you could modify a little bit. Basically for people who don't want/need to craft their design-system from scratch.

We don't have any concrete plans on it yet though.

**Comment by colmtuite** [comment]
@adenta Feel free to use this lib for your own projects. We currently use it across 6 projects at Modulz, including our websites and docs sites.

It's an extremely high-quality component lib. But be warned that it's intended for internal use only, and we make updates as we need, without any warning or consideration for outside projects. So it might be best to fork it instead.
