### ISSUE TITLE
Code block / Pre component

### ISSUE THREAD

**Issue by colmtuite** [modulz/radix#25]

**Comment by peduarte** [comment]
We've got a `Code` but not a `Pre`. Will add.

**Comment by colmtuite** [comment]
I think `CodeBlock` might be a better name? I think component names should be intuitive, not necessarily coupled to `html` tags.

**Comment by peduarte** [comment]
I think for Radix `Pre` is intuitive enough for developers using Radix, since they'd normally go for `pre`. But for Modulz I agree `Pre` is a bit like... 🤷‍♂️

**Comment by colmtuite** [comment]
Ok
