### ISSUE TITLE
[Dropdown Menu] Review right click functionality

### ISSUE THREAD

**Issue by raunofreiberg** [modulz/radix#265]
Hey 👋

The docs for Dropdown Menu mention:

> Useful for displaying a list of contextual actions on **right click.**

Though, I'm not sure how accurate or expected this is, considering there is a separate Right Click Menu. IMO, the Dropdown Menu should not respond to right clicks.

If opening the Dropdown Menu on right click is expected, then I think it should prevent the default behavior of opening the browser's right click menu:

![gif](https://gyazo.com/2c428c2c463c3b472ec77fbb99be3b4e.gif)

**Comment by peduarte** [comment]
Ooops, that's wrong. That's the desc for `RightClickMenu` Component.

FYI this style guide is out of date because it's been moved into Modulz. This is because all Modulz generated design systems will include style guides.

But since this is what's currently live for Radix, I agree it's worth updating. Thanks!

**Comment by raunofreiberg** [comment]
Yeah. In this case, I think Dropdown Menu should also not register right clicks.

Also, I'm sorry if these issues are redundant or something that you guys have already considered. I just enjoy thinking along and helping out wherever I notice something odd 😅

**Comment by peduarte** [comment]
Yeah, good point. And feel free to raise as many issues as you want! They’re helpful :) 

@benoitgrelard What do you think about cancelling right clicks on the Button here? Currently, it opens the Menu and the context menu.

**Comment by benoitgrelard** [comment]
I think it just shouldn't open on right click, we prevent that for our `Select` but forgot to apply the same here. I'm on it!

**Comment by peduarte** [comment]
Awesome, thanks! thanks @raunofreiberg will close this now.
