### ISSUE TITLE
[Slider] Knob does not move along when value is 0

### ISSUE THREAD

**Issue by raunofreiberg** [modulz/radix#271]
Title.

![gif](https://gyazo.com/d613e1689cf9bed0dae59f9062c5e90c.gif)

**Comment by peduarte** [comment]
Haha, I was waiting until someone came across this one 😂 

This happens because `0` is a falsy value. `value="0"` works. 

We've rebuilt this Primitive from scratch, so this issue will be gone once we update the dependency.

Thanks for raising and well spotted ;)
