### ISSUE TITLE
[Select] Options are not selectable on native mobile fallback

### ISSUE THREAD

**Issue by raunofreiberg** [modulz/radix#274]
Hey 👋

I noticed that something odd happens with the native fallback of Select when used with option groups. In particular, none of the options are selectable, even the ones not in a group.

Note: the example without option groups works fine!

[Here's a video of the issue at hand.](https://streamable.com/m1tsvy)

**Comment by raunofreiberg** [comment]
Interesting. This only happens on the mobile fallback! On desktop, it's fine.

![gif](https://gyazo.com/6c037aff8e03b68a75c5a0753385208e.gif)

**Comment by peduarte** [comment]
That's odd, we'll need to do some debugging to understand if it's an os issue or with our code. Thanks for raising!

**Comment by raunofreiberg** [comment]
The good news is that ya'll are clear on this! The bad news is that this seems to be a iOS Safari problem 😞

I tried using a [basic HTML option group](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_optgroup) example in iOS and it does not work at all!

[Here's a video.](https://streamable.com/4susdv)

**Comment by raunofreiberg** [comment]
It definitely looks like a OS specific thing. Apparently, it's possible to select options only by clicking on them, not navigating via scroll. 🤦‍♀️

[Here's an example.](https://streamable.com/5vz1fx)

**Comment by benoitgrelard** [comment]
It seems to be that when there are option groups, safari requires you to actually touch the option you want to select.

As opposed to when there are just options (no groups) it will let you roll the thing to land on an option and pressing "done" is enough to select it.

**Comment by raunofreiberg** [comment]
Yep, TIL. Sorry for the false alarm, feel free to close this! 😅

**Comment by benoitgrelard** [comment]
Haha no worries, TIL as well! To be honest seems like an odd decision, not sure why they went for that… Thanks for putting this through its paces though!
