### ISSUE TITLE
[List] Items have default button font family

### ISSUE THREAD

**Issue by raunofreiberg** [modulz/radix#275]
The computed font family of List items appears as Arial, which definitely looks off:

![image](https://user-images.githubusercontent.com/23662329/84034987-c64e3900-a9a3-11ea-8a02-b1af924df35a.png)

Instead, I think it should explicitly use the font family of the theme:

![image](https://user-images.githubusercontent.com/23662329/84035026-d7974580-a9a3-11ea-8774-1627bb0b7e64.png)

✌️

**Comment by peduarte** [comment]
haha well spotted. that's a deprecated component but feel free to open a PR for this one if you wish. Cheers!
