### ISSUE TITLE
[Avatar] Consider displaying initials

### ISSUE THREAD

**Issue by raunofreiberg** [modulz/radix#277]
Perhaps it would be nicer to truncate the name passed in as children and only display the initials?

![image](https://user-images.githubusercontent.com/23662329/84746711-0e321900-afbf-11ea-82f0-79d775db9915.png)

Bonus points if the full name is visible in a tooltip and announced by screen readers!

**Comment by benoitgrelard** [comment]
Hey @raunofreiberg,

We have considered this and ultimately settled on not automating too much as it can be quite opinionated. Some names are more complex than just first + last, etc. So we prefer giving full control.

That being said, we are currently re-considering the API (`children`) to something that is a bit more explicit like `initials` even though we still wouldn't automate anything.

Hope that makes sense.

**Comment by raunofreiberg** [comment]
It totally makes sense. Thanks for the response! I'm gonna close this 🙃
