### ISSUE TITLE
The source code of @modulz/primitives

### ISSUE THREAD

**Issue by isJaakko** [modulz/radix#286]
How do I get the source code of @modulz/primitives?
Now I can't find it in any repos.

**Comment by peduarte** [comment]
We're in the process of open sourcing the Modulz Primitives and should be ready in the next few weeks. Once they're ready, they will be made public and we'll be announced via our [Twitter](https://twitter.com/modulz), accompanied by documentation for every primitive. 

If you'd like early access, [reach out to Colm](https://twitter.com/colmtuite/status/1309452303217328129) and we'll invite you to the Discord channel.
