### ISSUE TITLE
Remove dat garbage focus ring in FF

### ISSUE THREAD

**Issue by colmtuite** [modulz/radix#44]

**Comment by peduarte** [comment]
Done, apart from `select` which I don't think it's currently possible.

The only way is to:
- make the color of the text `transparent`
- add a `text-shadow` of 1px and no blur to make the text visible again

This solution is way too hacky in my opinion - I prefer that the outline is visible until FF fixes the issue.

@colmtuite what do you think?

**Comment by colmtuite** [comment]
We need a custom `select` component. Let's forget about it until we implement that.
